/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 hacker-room-new.glb -T 
Files: hacker-room-new.glb [34.62MB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/hacker-room-new-transformed.glb [2.56MB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei';

const HackerRoom = (props) => {
  const { nodes, materials } = useGLTF('/models/scene.glb')
  const screenTxt = useTexture('textures/desk/screen.png');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.retro_computer_setup_retro_computer_setup_Mat_0.geometry}
        material={materials.retro_computer_setup_Mat}

        rotation={[-Math.PI / 2, 0, 0]}
      >
        
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/scene.glb')

export default HackerRoom;